"""Keywords for company breach / ransomware incident filtering."""

BREACH_SEARCH_KEYWORDS: list[str] = [
    "data breach",
    "breached",
    "breach",
    "ransomware",
    "cyberattack",
    "cyber attack",
    "hacked",
    "hackers",
    "stolen data",
    "leaked data",
    "leaked records",
    "customer data",
    "personal information",
    "incident response",
    "data leak",
    "extortion",
    "data leak site",
    "victim",
    "compromised",
    "credential theft",
    "account takeover",
    "supply chain attack",
    "lockbit",
    "clop",
    "blackcat",
    "play ransomware",
]
