from enum import Enum

from pydantic import BaseModel, Field


class SourceCategory(str, Enum):
    RESEARCHER_SOCIAL = "researcher_social"
    RESEARCHER_BLOG = "researcher_blog"
    CONFERENCE = "conference"
    VENDOR_ADVISORY = "vendor_advisory"
    VULNERABILITY = "vulnerability"
    DARK_WEB_INTEL = "dark_web_intel"
    COMPLIANCE = "compliance"
    COMPANY_BREACH_INTEL = "company_breach_intel"


class CollectionMethod(str, Enum):
    API = "api"
    RSS = "rss"
    HTML_SCRAPER = "html_scraper"
    JSON_FEED = "json_feed"
    GITHUB_API = "github_api"


class SourceConfig(BaseModel):
    id: str
    name: str
    category: SourceCategory
    url: str
    primary_method: CollectionMethod
    fallback_method: CollectionMethod | None = None
    feed_url: str | None = None
    api_endpoint: str | None = None
    trust_weight: float = Field(ge=0.0, le=1.0, default=0.5)
    requires_api_key: bool = False
    enabled: bool = True
    notes: str | None = None


SOURCE_REGISTRY: dict[str, SourceConfig] = {}

_sources: list[SourceConfig] = [
    # --- Researcher Social ---
    SourceConfig(
        id="twitter",
        name="X/Twitter (Nitter)",
        category=SourceCategory.RESEARCHER_SOCIAL,
        url="https://x.com",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.6,
        requires_api_key=False,
        notes="Searches via Nitter RSS/HTML — no Twitter API key needed",
    ),
    SourceConfig(
        id="linkedin",
        name="LinkedIn",
        category=SourceCategory.RESEARCHER_SOCIAL,
        url="https://www.linkedin.com",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.5,
        notes="Scraper-based; rate-limited",
    ),
    SourceConfig(
        id="reddit",
        name="Reddit",
        category=SourceCategory.RESEARCHER_SOCIAL,
        url="https://www.reddit.com",
        primary_method=CollectionMethod.API,
        api_endpoint="https://oauth.reddit.com/search",
        trust_weight=0.55,
        requires_api_key=True,
    ),
    SourceConfig(
        id="hackernews",
        name="Hacker News",
        category=SourceCategory.RESEARCHER_SOCIAL,
        url="https://news.ycombinator.com",
        primary_method=CollectionMethod.API,
        api_endpoint="https://hn.algolia.com/api/v1/search",
        trust_weight=0.65,
    ),
    SourceConfig(
        id="telegram",
        name="Telegram",
        category=SourceCategory.DARK_WEB_INTEL,
        url="https://telegram.org",
        primary_method=CollectionMethod.API,
        trust_weight=0.45,
        notes="Bot API / channel scraper for public threat channels",
    ),
    # --- Researcher Blogs ---
    SourceConfig(
        id="project_zero",
        name="Google Project Zero",
        category=SourceCategory.RESEARCHER_BLOG,
        url="https://projectzero.google",
        primary_method=CollectionMethod.RSS,
        feed_url="https://googleprojectzero.blogspot.com/feeds/posts/default",
        trust_weight=0.95,
    ),
    SourceConfig(
        id="krebsonsecurity",
        name="KrebsOnSecurity",
        category=SourceCategory.RESEARCHER_BLOG,
        url="https://krebsonsecurity.com",
        primary_method=CollectionMethod.RSS,
        feed_url="https://krebsonsecurity.com/feed/",
        trust_weight=0.9,
    ),
    SourceConfig(
        id="watchtowr",
        name="watchTowr Labs",
        category=SourceCategory.RESEARCHER_BLOG,
        url="https://labs.watchtowr.com",
        primary_method=CollectionMethod.RSS,
        feed_url="https://labs.watchtowr.com/rss/",
        trust_weight=0.88,
    ),
    SourceConfig(
        id="unit42",
        name="Palo Alto Unit42",
        category=SourceCategory.RESEARCHER_BLOG,
        url="https://unit42.paloaltonetworks.com",
        primary_method=CollectionMethod.RSS,
        feed_url="https://unit42.paloaltonetworks.com/feed/",
        trust_weight=0.92,
    ),
    SourceConfig(
        id="dfir_report",
        name="DFIR Report",
        category=SourceCategory.RESEARCHER_BLOG,
        url="https://thedfirreport.com",
        primary_method=CollectionMethod.RSS,
        feed_url="https://thedfirreport.com/feed/",
        trust_weight=0.9,
    ),
    SourceConfig(
        id="sophos_xops",
        name="Sophos X-Ops",
        category=SourceCategory.RESEARCHER_BLOG,
        url="https://news.sophos.com/en-us/category/threat-research",
        primary_method=CollectionMethod.RSS,
        feed_url="https://news.sophos.com/en-us/category/threat-research/feed/",
        trust_weight=0.88,
    ),
    SourceConfig(
        id="orange_cyberdefense",
        name="Orange Cyberdefense",
        category=SourceCategory.RESEARCHER_BLOG,
        url="https://www.orangecyberdefense.com/global/blog",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.orangecyberdefense.com/global/blog/feed/",
        trust_weight=0.85,
    ),
    SourceConfig(
        id="sans_isc",
        name="SANS ISC",
        category=SourceCategory.RESEARCHER_BLOG,
        url="https://isc.sans.edu",
        primary_method=CollectionMethod.RSS,
        feed_url="https://isc.sans.edu/rssfeed_full.xml",
        trust_weight=0.9,
    ),
    SourceConfig(
        id="rapid7",
        name="Rapid7 Blog",
        category=SourceCategory.RESEARCHER_BLOG,
        url="https://www.rapid7.com/blog",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.rapid7.com/blog/rss/",
        trust_weight=0.85,
    ),
    SourceConfig(
        id="tenable",
        name="Tenable Blog",
        category=SourceCategory.RESEARCHER_BLOG,
        url="https://www.tenable.com/blog",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.tenable.com/blog/feed",
        trust_weight=0.85,
    ),
    # --- Conference ---
    SourceConfig(
        id="blackhat",
        name="Black Hat",
        category=SourceCategory.CONFERENCE,
        url="https://www.blackhat.com",
        primary_method=CollectionMethod.RSS,
        trust_weight=0.8,
    ),
    SourceConfig(
        id="defcon",
        name="DEF CON",
        category=SourceCategory.CONFERENCE,
        url="https://defcon.org",
        primary_method=CollectionMethod.RSS,
        trust_weight=0.8,
    ),
    # --- Vendor Advisories ---
    SourceConfig(
        id="msrc",
        name="Microsoft MSRC",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://msrc.microsoft.com/update-guide",
        primary_method=CollectionMethod.API,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        api_endpoint="https://api.msrc.microsoft.com/cvrf/v2.0/updates",
        trust_weight=0.98,
    ),
    SourceConfig(
        id="cisco_advisories",
        name="Cisco Advisories",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://sec.cloudapps.cisco.com/security/center/publicationListing.x",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://sec.cloudapps.cisco.com/security/center/psirtrss20/CiscoSecurityAdvisory.xml",
        trust_weight=0.97,
    ),
    SourceConfig(
        id="fortinet_psirt",
        name="Fortinet PSIRT",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://www.fortiguard.com/psirt",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://filestore.fortinet.com/fortiguard/rss/ir.xml",
        trust_weight=0.97,
    ),
    SourceConfig(
        id="palo_alto_advisories",
        name="Palo Alto Advisories",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://security.paloaltonetworks.com",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://security.paloaltonetworks.com/rss.xml",
        trust_weight=0.97,
    ),
    SourceConfig(
        id="vmware_advisories",
        name="VMware/Broadcom Advisories",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://support.broadcom.com/web/ecx/security-advisory",
        primary_method=CollectionMethod.HTML_SCRAPER,
        fallback_method=CollectionMethod.RSS,
        trust_weight=0.96,
    ),
    SourceConfig(
        id="ivanti_advisories",
        name="Ivanti Advisories",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://www.ivanti.com/security/advisories",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://www.ivanti.com/blog/rss.xml",
        trust_weight=0.96,
    ),
    SourceConfig(
        id="citrix_bulletins",
        name="Citrix Bulletins",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://support.citrix.com/securitybulletins",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.96,
    ),
    SourceConfig(
        id="juniper_advisories",
        name="Juniper Advisories",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://supportportal.juniper.net/s/securityadvisories",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.96,
    ),
    SourceConfig(
        id="chrome_releases",
        name="Google Chrome Releases",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://chromereleases.googleblog.com",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://chromereleases.googleblog.com/feeds/posts/default",
        trust_weight=0.95,
    ),
    SourceConfig(
        id="adobe_security",
        name="Adobe Security Bulletins",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://helpx.adobe.com/security.html",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.95,
    ),
    SourceConfig(
        id="apple_security",
        name="Apple Security Releases",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://support.apple.com/security-releases",
        primary_method=CollectionMethod.HTML_SCRAPER,
        fallback_method=CollectionMethod.RSS,
        trust_weight=0.95,
    ),
    SourceConfig(
        id="oracle_security",
        name="Oracle Security Alerts",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://www.oracle.com/security-alerts",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://www.oracle.com/security-alerts/rss.xml",
        trust_weight=0.95,
    ),
    SourceConfig(
        id="sap_security",
        name="SAP Security Notes",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://support.sap.com/en/my-support/knowledge-base/security-notes-news.html",
        primary_method=CollectionMethod.API,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.95,
        requires_api_key=True,
        notes="SAP API requires account",
    ),
    SourceConfig(
        id="atlassian_security",
        name="Atlassian Security",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://confluence.atlassian.com/security",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://confluence.atlassian.com/creators/feed.action?types=page&spaces=security",
        trust_weight=0.95,
    ),
    SourceConfig(
        id="gitlab_security",
        name="GitLab Security",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://about.gitlab.com/releases",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.GITHUB_API,
        feed_url="https://about.gitlab.com/all-releases.xml",
        trust_weight=0.95,
    ),
    SourceConfig(
        id="manageengine_security",
        name="ManageEngine Security",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://www.manageengine.com/security.html",
        primary_method=CollectionMethod.HTML_SCRAPER,
        fallback_method=CollectionMethod.RSS,
        trust_weight=0.94,
    ),
    SourceConfig(
        id="aws_security",
        name="AWS Security Bulletins",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://aws.amazon.com/security/security-bulletins",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://aws.amazon.com/security/security-bulletins/feed/",
        trust_weight=0.96,
    ),
    SourceConfig(
        id="gcp_security",
        name="Google Cloud Bulletins",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://cloud.google.com/support/bulletins",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://cloud.google.com/feeds/cloud-security-bulletins.xml",
        trust_weight=0.96,
    ),
    SourceConfig(
        id="docker_security",
        name="Docker Security",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://docs.docker.com/security/security-announcements",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.94,
    ),
    SourceConfig(
        id="hashicorp_security",
        name="HashiCorp Security",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://discuss.hashicorp.com/c/security/security-announcements",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://discuss.hashicorp.com/c/security/security-announcements.rss",
        trust_weight=0.94,
    ),
    SourceConfig(
        id="kubernetes_security",
        name="Kubernetes Security",
        category=SourceCategory.VENDOR_ADVISORY,
        url="https://kubernetes.io/docs/reference/issues-security/",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.GITHUB_API,
        trust_weight=0.95,
    ),
    # --- Vulnerability Sources ---
    SourceConfig(
        id="cve_program",
        name="CVE Program",
        category=SourceCategory.VULNERABILITY,
        url="https://www.cve.org",
        primary_method=CollectionMethod.API,
        api_endpoint="https://cveawg.mitre.org/api/cve",
        trust_weight=0.99,
    ),
    SourceConfig(
        id="nvd",
        name="NVD",
        category=SourceCategory.VULNERABILITY,
        url="https://nvd.nist.gov",
        primary_method=CollectionMethod.API,
        api_endpoint="https://services.nvd.nist.gov/rest/json/cves/2.0",
        trust_weight=0.99,
        requires_api_key=False,
        notes="API key optional for higher rate limits",
    ),
    SourceConfig(
        id="cisa_kev",
        name="CISA KEV",
        category=SourceCategory.VULNERABILITY,
        url="https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
        primary_method=CollectionMethod.JSON_FEED,
        api_endpoint="https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json",
        trust_weight=1.0,
    ),
    SourceConfig(
        id="github_poc",
        name="GitHub PoC",
        category=SourceCategory.VULNERABILITY,
        url="https://github.com",
        primary_method=CollectionMethod.GITHUB_API,
        api_endpoint="https://api.github.com/search/repositories",
        trust_weight=0.85,
        requires_api_key=False,
        notes="GitHub token optional for higher rate limits",
    ),
    SourceConfig(
        id="exploit_db",
        name="Exploit-DB",
        category=SourceCategory.VULNERABILITY,
        url="https://www.exploit-db.com",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        feed_url="https://www.exploit-db.com/rss.xml",
        trust_weight=0.88,
    ),
    SourceConfig(
        id="metasploit",
        name="Metasploit",
        category=SourceCategory.VULNERABILITY,
        url="https://github.com/rapid7/metasploit-framework",
        primary_method=CollectionMethod.GITHUB_API,
        api_endpoint="https://api.github.com/search/code",
        trust_weight=0.87,
        requires_api_key=False,
    ),
    SourceConfig(
        id="packetstorm",
        name="PacketStorm",
        category=SourceCategory.VULNERABILITY,
        url="https://packetstormsecurity.com",
        primary_method=CollectionMethod.RSS,
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.82,
    ),
    # --- Compliance Intelligence ---
    SourceConfig(
        id="nist_compliance",
        name="NIST",
        category=SourceCategory.COMPLIANCE,
        url="https://www.nist.gov",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.nist.gov/news-events/cybersecurity/rss.xml",
        trust_weight=0.98,
        notes="Tier 1 — NIST cybersecurity and compliance guidance",
    ),
    SourceConfig(
        id="cisa_guidance",
        name="CISA Guidance",
        category=SourceCategory.COMPLIANCE,
        url="https://www.cisa.gov",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.cisa.gov/cybersecurity-advisories.xml",
        trust_weight=0.97,
        notes="Tier 1 — CISA compliance and guidance",
    ),
    SourceConfig(
        id="enisa",
        name="ENISA",
        category=SourceCategory.COMPLIANCE,
        url="https://www.enisa.europa.eu",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.enisa.europa.eu/media/news-items/news-wires/RSS",
        trust_weight=0.97,
        notes="Tier 1 — EU cybersecurity agency",
    ),
    SourceConfig(
        id="ec_digital",
        name="European Commission Digital Strategy",
        category=SourceCategory.COMPLIANCE,
        url="https://digital-strategy.ec.europa.eu",
        primary_method=CollectionMethod.RSS,
        feed_url="https://digital-strategy.ec.europa.eu/en/news/rss.xml",
        trust_weight=0.95,
    ),
    SourceConfig(
        id="uk_ncsc",
        name="UK NCSC",
        category=SourceCategory.COMPLIANCE,
        url="https://www.ncsc.gov.uk",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.ncsc.gov.uk/api/1/services/v1/report-rss-feed.xml",
        trust_weight=0.96,
    ),
    SourceConfig(
        id="hhs_ocr_hipaa",
        name="HHS OCR (HIPAA)",
        category=SourceCategory.COMPLIANCE,
        url="https://www.hhs.gov/hipaa",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.hhs.gov/about/news/index.xml",
        trust_weight=0.94,
    ),
    SourceConfig(
        id="sec_cybersecurity",
        name="SEC Cybersecurity Rules",
        category=SourceCategory.COMPLIANCE,
        url="https://www.sec.gov",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.sec.gov/news/pressreleases.rss",
        trust_weight=0.95,
    ),
    SourceConfig(
        id="iso_compliance",
        name="ISO",
        category=SourceCategory.COMPLIANCE,
        url="https://www.iso.org",
        primary_method=CollectionMethod.HTML_SCRAPER,
        fallback_method=CollectionMethod.RSS,
        trust_weight=0.98,
        notes="Tier 1 — ISO standards updates",
    ),
    SourceConfig(
        id="pci_ssc",
        name="PCI SSC",
        category=SourceCategory.COMPLIANCE,
        url="https://www.pcisecuritystandards.org",
        primary_method=CollectionMethod.RSS,
        feed_url="https://blog.pcisecuritystandards.org/rss.xml",
        trust_weight=0.97,
        notes="Tier 1 — PCI DSS standards body",
    ),
    SourceConfig(
        id="csa",
        name="Cloud Security Alliance",
        category=SourceCategory.COMPLIANCE,
        url="https://cloudsecurityalliance.org",
        primary_method=CollectionMethod.RSS,
        feed_url="https://cloudsecurityalliance.org/blog/feed/",
        trust_weight=0.92,
    ),
    SourceConfig(
        id="cis_controls",
        name="CIS Controls",
        category=SourceCategory.COMPLIANCE,
        url="https://www.cisecurity.org",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.cisecurity.org/feed",
        trust_weight=0.93,
    ),
    SourceConfig(
        id="owasp_compliance",
        name="OWASP",
        category=SourceCategory.COMPLIANCE,
        url="https://owasp.org",
        primary_method=CollectionMethod.RSS,
        feed_url="https://owasp.org/news/rss/",
        trust_weight=0.90,
    ),
    SourceConfig(
        id="isaca",
        name="ISACA",
        category=SourceCategory.COMPLIANCE,
        url="https://www.isaca.org",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.isaca.org/resources/news-and-trends/isaca-now-blog/rss",
        trust_weight=0.91,
    ),
    SourceConfig(
        id="iapp",
        name="IAPP",
        category=SourceCategory.COMPLIANCE,
        url="https://iapp.org",
        primary_method=CollectionMethod.RSS,
        feed_url="https://iapp.org/news/rss/",
        trust_weight=0.94,
        notes="Tier 1 — privacy and compliance research",
    ),
    SourceConfig(
        id="sans_compliance",
        name="SANS Compliance",
        category=SourceCategory.COMPLIANCE,
        url="https://www.sans.org",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.sans.org/blog/feed.xml",
        trust_weight=0.90,
    ),
    SourceConfig(
        id="gartner_compliance",
        name="Gartner",
        category=SourceCategory.COMPLIANCE,
        url="https://www.gartner.com",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.80,
        notes="Research — may require subscription for full access",
    ),
    SourceConfig(
        id="forrester_compliance",
        name="Forrester",
        category=SourceCategory.COMPLIANCE,
        url="https://www.forrester.com",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.80,
    ),
    SourceConfig(
        id="microsoft_compliance",
        name="Microsoft Compliance",
        category=SourceCategory.COMPLIANCE,
        url="https://www.microsoft.com/en-us/trust-center/compliance",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.88,
        notes="Tier 2 — vendor compliance portal",
    ),
    SourceConfig(
        id="microsoft_compliance_blog",
        name="Microsoft Compliance Blog",
        category=SourceCategory.COMPLIANCE,
        url="https://www.microsoft.com/en-us/security/blog",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.microsoft.com/en-us/security/blog/feed/",
        trust_weight=0.87,
    ),
    SourceConfig(
        id="microsoft_service_trust",
        name="Microsoft Service Trust Portal",
        category=SourceCategory.COMPLIANCE,
        url="https://servicetrust.microsoft.com",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.88,
        notes="Tier 2",
    ),
    SourceConfig(
        id="aws_compliance",
        name="AWS Compliance Programs",
        category=SourceCategory.COMPLIANCE,
        url="https://aws.amazon.com/compliance",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.88,
        notes="Tier 2",
    ),
    SourceConfig(
        id="aws_compliance_blog",
        name="AWS Security Blog",
        category=SourceCategory.COMPLIANCE,
        url="https://aws.amazon.com/blogs/security",
        primary_method=CollectionMethod.RSS,
        feed_url="https://aws.amazon.com/blogs/security/feed/",
        trust_weight=0.87,
    ),
    SourceConfig(
        id="gcp_compliance",
        name="Google Cloud Compliance",
        category=SourceCategory.COMPLIANCE,
        url="https://cloud.google.com/security/compliance",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.88,
        notes="Tier 2",
    ),
    SourceConfig(
        id="oracle_compliance",
        name="Oracle Compliance Documentation",
        category=SourceCategory.COMPLIANCE,
        url="https://www.oracle.com/corporate/security-practices",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.86,
        notes="Tier 2",
    ),
    SourceConfig(
        id="sap_trust_center",
        name="SAP Trust Center",
        category=SourceCategory.COMPLIANCE,
        url="https://www.sap.com/about/trust-center.html",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.86,
        notes="Tier 2",
    ),
    SourceConfig(
        id="salesforce_compliance",
        name="Salesforce Compliance Center",
        category=SourceCategory.COMPLIANCE,
        url="https://compliance.salesforce.com",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.86,
        notes="Tier 2",
    ),
    SourceConfig(
        id="servicenow_compliance",
        name="ServiceNow Compliance Resources",
        category=SourceCategory.COMPLIANCE,
        url="https://www.servicenow.com/trust/compliance.html",
        primary_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.85,
    ),
    SourceConfig(
        id="edpb",
        name="European Data Protection Board (EDPB)",
        category=SourceCategory.COMPLIANCE,
        url="https://www.edpb.europa.eu",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.edpb.europa.eu/news/news_en/rss.xml",
        trust_weight=0.97,
        notes="Tier 1 — privacy regulator",
    ),
    SourceConfig(
        id="ico_uk",
        name="ICO UK",
        category=SourceCategory.COMPLIANCE,
        url="https://ico.org.uk",
        primary_method=CollectionMethod.RSS,
        feed_url="https://ico.org.uk/about-the-ico/media-centre/news-and-blogs/rss/",
        trust_weight=0.95,
    ),
    SourceConfig(
        id="eu_ai_act",
        name="EU AI Act",
        category=SourceCategory.COMPLIANCE,
        url="https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",
        primary_method=CollectionMethod.RSS,
        feed_url="https://digital-strategy.ec.europa.eu/en/news/rss.xml",
        trust_weight=0.98,
        notes="Tier 1 — AI governance",
    ),
    SourceConfig(
        id="nist_ai_rmf",
        name="NIST AI RMF",
        category=SourceCategory.COMPLIANCE,
        url="https://www.nist.gov/itl/ai-risk-management-framework",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.nist.gov/news-events/cybersecurity/rss.xml",
        trust_weight=0.97,
    ),
    SourceConfig(
        id="iso_42001",
        name="ISO 42001 Information",
        category=SourceCategory.COMPLIANCE,
        url="https://www.iso.org/standard/81230.html",
        primary_method=CollectionMethod.HTML_SCRAPER,
        fallback_method=CollectionMethod.RSS,
        trust_weight=0.96,
    ),
    # --- Company breach news (Tier 1) ---
    SourceConfig(
        id="bleepingcomputer",
        name="BleepingComputer",
        category=SourceCategory.COMPANY_BREACH_INTEL,
        url="https://www.bleepingcomputer.com",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.bleepingcomputer.com/feed/",
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.88,
    ),
    SourceConfig(
        id="securityweek",
        name="SecurityWeek",
        category=SourceCategory.COMPANY_BREACH_INTEL,
        url="https://www.securityweek.com",
        primary_method=CollectionMethod.RSS,
        feed_url="https://feeds.feedburner.com/securityweek",
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.85,
    ),
    SourceConfig(
        id="the_hacker_news",
        name="The Hacker News",
        category=SourceCategory.COMPANY_BREACH_INTEL,
        url="https://thehackernews.com",
        primary_method=CollectionMethod.RSS,
        feed_url="https://feeds.feedburner.com/TheHackersNews",
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.86,
    ),
    SourceConfig(
        id="ransomware_live",
        name="Ransomware.live",
        category=SourceCategory.COMPANY_BREACH_INTEL,
        url="https://www.ransomware.live",
        primary_method=CollectionMethod.RSS,
        feed_url="https://www.ransomware.live/rss.xml",
        fallback_method=CollectionMethod.HTML_SCRAPER,
        trust_weight=0.9,
        notes="Ransomware victim disclosures and group activity",
    ),
    # --- Dark Web / Intel ---
    SourceConfig(
        id="intelx",
        name="IntelX.io",
        category=SourceCategory.DARK_WEB_INTEL,
        url="https://intelx.io",
        primary_method=CollectionMethod.API,
        trust_weight=0.7,
        requires_api_key=True,
        notes="Free tier: 100 searches/month",
    ),
    SourceConfig(
        id="haveibeenpwned",
        name="Have I Been Pwned",
        category=SourceCategory.DARK_WEB_INTEL,
        url="https://haveibeenpwned.com",
        primary_method=CollectionMethod.API,
        trust_weight=0.75,
        requires_api_key=True,
        notes="Free rate-limited API",
    ),
]

for _src in _sources:
    SOURCE_REGISTRY[_src.id] = _src


def get_sources_by_category(
    category: SourceCategory | None = None,
) -> list[SourceConfig]:
    if category is None:
        return list(SOURCE_REGISTRY.values())
    return [s for s in SOURCE_REGISTRY.values() if s.category == category]


def get_enabled_sources(
    source_ids: list[str] | None = None,
) -> list[SourceConfig]:
    if source_ids:
        return [
            SOURCE_REGISTRY[sid]
            for sid in source_ids
            if sid in SOURCE_REGISTRY and SOURCE_REGISTRY[sid].enabled
        ]
    return [s for s in SOURCE_REGISTRY.values() if s.enabled]
